# Generated by Django 2.2 on 2020-11-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmHub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='elegido',
            field=models.BooleanField(default=False),
        ),
    ]
