# Generated by Django 2.2 on 2020-11-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmHub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='precio_base',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
