# Generated by Django 2.2 on 2020-11-17 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FilmHub', '0002_pelicula_precio_base'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boleto',
            old_name='valor',
            new_name='monto_total',
        ),
    ]
