# Generated by Django 2.2 on 2020-11-18 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FilmHub', '0002_paquete_fecha_y_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete',
            name='fecha_y_hora',
        ),
    ]
