# Generated by Django 2.2 on 2020-11-17 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FilmHub', '0003_auto_20201117_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_final', models.IntegerField(blank=True, default=0, null=True)),
                ('boleto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FilmHub.Boleto')),
                ('combo_comida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FilmHub.Combo_Comida')),
            ],
        ),
    ]
