# Generated by Django 2.2 on 2020-11-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmHub', '0005_auto_20201119_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(default='default.jpg', upload_to='portadas'),
        ),
    ]
