# Generated by Django 2.2 on 2020-11-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmHub', '0006_pelicula_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='imagen',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='portada',
            field=models.ImageField(default='default.jpg', upload_to='static/portadas'),
        ),
    ]
