# Generated by Django 2.2 on 2020-12-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmHub', '0011_auto_20201202_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleto',
            name='asiento',
        ),
        migrations.AddField(
            model_name='boleto',
            name='asientos',
            field=models.ManyToManyField(null=True, to='FilmHub.Asiento'),
        ),
    ]
