# Generated by Django 2.2 on 2020-12-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmHub', '0012_auto_20201202_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='reservado',
            field=models.BooleanField(default=False),
        ),
    ]
