# Generated by Django 2.2 on 2020-12-03 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FilmHub', '0013_asiento_reservado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='funcion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FilmHub.Funcion'),
        ),
    ]
