# Generated by Django 2.2 on 2020-12-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmHub', '0014_auto_20201203_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='asientos',
            field=models.ManyToManyField(blank=True, to='FilmHub.Asiento'),
        ),
    ]
