# Generated by Django 2.2 on 2020-12-03 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FilmHub', '0015_auto_20201203_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo_comida',
            name='bebida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FilmHub.Bebida'),
        ),
        migrations.AlterField(
            model_name='combo_comida',
            name='comida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FilmHub.Comida'),
        ),
    ]
