# Generated by Django 2.2 on 2020-12-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmHub', '0017_funcion_asientos_reservados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcion',
            name='asientos_reservados',
            field=models.ManyToManyField(blank=True, null=True, to='FilmHub.Asiento'),
        ),
    ]
